#pragma once

#include "litiv/utils/ParallelUtils.hpp"
#include <opencv2/video/background_segm.hpp>

class BackgroundSubtractorImpl :
        public cv::BackgroundSubtractor {
public:
    //! default constructor
    BackgroundSubtractorImpl(size_t nROIBorderSize);

    //! (re)initiaization method; needs to be called before starting background subtraction (assumes no specific ROI)
    virtual void initialize(const cv::Mat& oInitImg);
    //! (re)initiaization method; needs to be called before starting background subtraction
    virtual void initialize(const cv::Mat& oInitImg, const cv::Mat& oROI);
    //! unused, always returns nullptr
    virtual cv::AlgorithmInfo* info() const {return nullptr;}
    //! returns the default learning rate value used in 'apply'
    virtual double getDefaultLearningRate() const = 0;
    //! turns automatic model reset on or off
    virtual void setAutomaticModelReset(bool);
    //! modifies the given ROI so it will not cause lookup errors near borders when used in the processing step
    virtual void validateROI(cv::Mat& oROI);
    //! sets the ROI to be used for input analysis (note: this function will reinit the model and return the validated ROI)
    virtual void setROI(cv::Mat& oROI);
    //! returns a copy of the ROI used for input analysis
    cv::Mat getROICopy() const;

protected:

    struct PxInfoBase {
        int nImgCoord_Y;
        int nImgCoord_X;
        size_t nModelIdx;
    };

    //! background model ROI used for input analysis (specific to the input image size)
    cv::Mat m_oROI;
    //! input image size
    cv::Size m_oImgSize;
    //! ROI border size to be ignored, useful for descriptor-based methods
    size_t m_nROIBorderSize;
    //! input image channel size
    size_t m_nImgChannels;
    //! input image type
    int m_nImgType;
    //! total number of pixels (depends on the input frame size) & total number of relevant pixels
    size_t m_nTotPxCount, m_nTotRelevantPxCount;
    //! total number of ROI pixels before & after border cleanup
    size_t m_nOrigROIPxCount, m_nFinalROIPxCount;
    //! current frame index, frame count since last model reset & model reset cooldown counters
    size_t m_nFrameIdx, m_nFramesSinceLastReset, m_nModelResetCooldown;
    //! internal pixel index LUT for all relevant analysis regions (based on the provided ROI)
    std::vector<size_t> m_vnPxIdxLUT;
    //! internal pixel info LUT for all possible pixel indexes
    std::vector<PxInfoBase> m_voPxInfoLUT;
    //! specifies whether the algorithm parameters are fully initialized or not (must be handled by derived class)
    bool m_bInitialized;
    //! specifies whether the model has been fully initialized or not (must be handled by derived class)
    bool m_bModelInitialized;
    //! specifies whether automatic model resets are enabled or not
    bool m_bAutoModelResetEnabled;
    //! specifies whether the camera is considered moving or not
    bool m_bUsingMovingCamera;
    //! the foreground mask generated by the method at [t-1]
    cv::Mat m_oLastFGMask;
    //! copy of latest pixel intensities (used when refreshing model)
    cv::Mat m_oLastColorFrame;

private:
    BackgroundSubtractorImpl& operator=(const BackgroundSubtractorImpl&) = delete;
    BackgroundSubtractorImpl(const BackgroundSubtractorImpl&) = delete;

public:
    // #### for debug purposes only ####
    int m_nDebugCoordX, m_nDebugCoordY;
    std::string m_sDebugName;
    cv::FileStorage* m_pDebugFS;
};

template<ParallelUtils::eParallelImplType eImpl=ParallelUtils::eParallelImpl_None, typename enable=void>
class BackgroundSubtractorParallelImpl;

#if HAVE_GLSL
template<ParallelUtils::eParallelImplType eImpl>
class BackgroundSubtractorParallelImpl<eImpl, typename std::enable_if<eImpl==ParallelUtils::eParallelImpl_GLSL>::type> :
        public ParallelUtils::ParallelImpl_GLSL,
        public BackgroundSubtractorImpl {
public:
    //! glsl impl constructor
    BackgroundSubtractorParallelImpl(size_t nLevels, size_t nComputeStages, size_t nExtraSSBOs, size_t nExtraACBOs,
                                     size_t nExtraImages, size_t nExtraTextures, int nDebugType, bool bUseDisplay,
                                     bool bUseTimers, bool bUseIntegralFormat);

    //! returns a copy of the latest foreground mask
    void getLatestForegroundMask(cv::OutputArray _oLastFGMask);
    //! model update/segmentation function (asynchronous version, glsl interface); the learning param is used to override the internal learning speed
    void apply_async_glimpl(cv::InputArray _oNextImage, bool bRebindAll, double dLearningRate=-1);
    //! model update/segmentation function (asynchronous version); the learning param is used to override the internal learning speed
    void apply_async(cv::InputArray oNextImage, double dLearningRate=-1);
    //! model update/segmentation function (asynchronous version); the learning param is used to override the internal learning speed
    void apply_async(cv::InputArray oNextImage, cv::OutputArray oLastFGMask, double dLearningRate=-1);
    //! overloads 'apply' from cv::BackgroundSubtractor and redirects it to apply_async
    virtual void apply(cv::InputArray oNextImage, cv::OutputArray oLastFGMask, double dLearningRate=-1);

protected:
    //! used to pass 'apply' learning rate parameter to overloaded dispatch call, if needed
    double m_dCurrLearningRate;
};
typedef BackgroundSubtractorParallelImpl<ParallelUtils::eParallelImpl_GLSL> BackgroundSubtractorImpl_GLSL;
#endif //!HAVE_GLSL

#if HAVE_CUDA
template<ParallelUtils::eParallelImplType eImpl>
class BackgroundSubtractorParallelImpl<eImpl, typename std::enable_if<eImpl==ParallelUtils::eParallelImpl_CUDA>::type> :
        public ParallelUtils::ParallelImpl_CUDA,
        public BackgroundSubtractorImpl {
        static_assert(false,"Missing CUDA impl");
};
typedef BackgroundSubtractorParallelImpl<ParallelUtils::eParallelImpl_CUDA> BackgroundSubtractorImpl_CUDA;
#endif //HAVE_CUDA

#if HAVE_OPENCL
template<ParallelUtils::eParallelImplType eImpl>
class BackgroundSubtractorParallelImpl<eImpl, typename std::enable_if<eImpl==ParallelUtils::eParallelImpl_OpenCL>::type> :
        public ParallelUtils::ParallelImpl_OpenCL,
        public BackgroundSubtractorImpl {
        static_assert(false,"Missing OpenCL impl");
};
typedef BackgroundSubtractorParallelImpl<ParallelUtils::eParallelImpl_OpenCL> BackgroundSubtractorImpl_OpenCL;
#endif //HAVE_OPENCL

template<ParallelUtils::eParallelImplType eImpl>
class BackgroundSubtractorParallelImpl<eImpl, typename std::enable_if<eImpl==ParallelUtils::eParallelImpl_None>::type> :
        public ParallelUtils::NoParallelImpl,
        public BackgroundSubtractorImpl {
public:
    //! default impl constructor
    BackgroundSubtractorParallelImpl(size_t nROIBorderSize);
};
